// Scan every sprite the game ships and distil the REAL palette + style norms from them.
//
//   node spritefactory/extract-palette.mjs
//
// Writes:
//   spritefactory/lib/palette-data.mjs   — generated palette module (source of truth for the factory)
//   spritefactory/reports/palette-report.txt — human-readable audit: colours by family, per-sprite stats
//
// Everything the analyzer later enforces ("stay on the game palette", "alpha is binary", "sprites
// are 16×16 frames") is *measured* here, not assumed — rerun after adding official art.

import fs from 'node:fs';
import path from 'node:path';
import { readPng } from './lib/png.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const ASSETS = path.join(ROOT, 'public', 'assets');

const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
  const p = path.join(dir, e.name);
  return e.isDirectory() ? walk(p) : p.endsWith('.png') ? [p] : [];
});

const files = walk(ASSETS);

const colorKey = (r, g, b) => (r << 16) | (g << 8) | b;
const hex = (k) => `#${k.toString(16).padStart(6, '0')}`;

// colour → { px: total pixels, files: Set of files }
const colors = new Map();
const perFile = [];

for (const file of files) {
  let img;
  try { img = readPng(file); } catch (e) {
    console.warn(`skip ${path.relative(ASSETS, file)}: ${e.message}`);
    continue;
  }
  const { width, height, data } = img;
  const fileColors = new Set();
  let opaque = 0; let transparent = 0; let semi = 0;
  for (let i = 0; i < data.length; i += 4) {
    const a = data[i + 3];
    if (a === 0) { transparent += 1; continue; }
    if (a < 255) { semi += 1; continue; }
    opaque += 1;
    const k = colorKey(data[i], data[i + 1], data[i + 2]);
    fileColors.add(k);
    const entry = colors.get(k) ?? { px: 0, files: new Set() };
    entry.px += 1;
    entry.files.add(file);
    colors.set(k, entry);
  }
  perFile.push({
    file: path.relative(ASSETS, file).replaceAll('\\', '/'),
    width, height,
    colors: fileColors.size,
    opaque, transparent, semi,
  });
}

// ---------------------------------------------------------------------------------------------
// Classify colours into families by hue/level so the palette reads as ramps, not a soup.
const toHsl = (k) => {
  const r = ((k >> 16) & 255) / 255; const g = ((k >> 8) & 255) / 255; const b = (k & 255) / 255;
  const max = Math.max(r, g, b); const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return { h: 0, s: 0, l };
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
  else if (max === g) h = ((b - r) / d + 2) / 6;
  else h = ((r - g) / d + 4) / 6;
  return { h: h * 360, s, l };
};

const family = (k) => {
  const { h, s, l } = toHsl(k);
  if (s < 0.12) return l < 0.16 ? 'outline/black' : l > 0.85 ? 'white' : 'gray';
  if (h < 15 || h >= 345) return 'red';
  if (h < 45) return 'orange/brown';
  if (h < 70) return 'yellow';
  if (h < 170) return 'green';
  if (h < 260) return 'blue';
  if (h < 345) return 'purple/pink';
  return 'other';
};

const sorted = [...colors.entries()].sort((a, b) => b[1].px - a[1].px);

// The canonical palette: colours that carry real coverage — present in 2+ files OR heavy in one.
const CANON = sorted.filter(([, v]) => v.files.size >= 2 || v.px >= 200);

const byFamily = new Map();
for (const [k, v] of CANON) {
  const f = family(k);
  if (!byFamily.has(f)) byFamily.set(f, []);
  byFamily.get(f).push([k, v]);
}
for (const list of byFamily.values()) list.sort((a, b) => toHsl(a[0]).l - toHsl(b[0]).l);

// ---------------------------------------------------------------------------------------------
// Emit the generated module.
const genLines = [
  '// GENERATED by spritefactory/extract-palette.mjs — do not edit by hand; rerun the extractor.',
  `// Source: ${files.length} PNGs under public/assets. Colours seen in 2+ files or with 200+ px.`,
  '',
  'export const GAME_PALETTE = [',
];
for (const [fam, list] of [...byFamily.entries()].sort()) {
  genLines.push(`  // ${fam}`);
  for (const [k, v] of list) {
    genLines.push(`  { hex: '${hex(k)}', rgb: [${(k >> 16) & 255}, ${(k >> 8) & 255}, ${k & 255}], px: ${v.px}, files: ${v.files.size}, family: '${fam}' },`);
  }
}
genLines.push('];', '');
fs.mkdirSync(path.join(ROOT, 'spritefactory', 'lib'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'spritefactory', 'lib', 'palette-data.mjs'), genLines.join('\n'));

// ---------------------------------------------------------------------------------------------
// Human-readable report.
const rep = [];
rep.push(`Palette audit — ${files.length} PNGs, ${colors.size} distinct opaque colours, ${CANON.length} canonical.`);
rep.push('');
for (const [fam, list] of [...byFamily.entries()].sort()) {
  rep.push(`== ${fam} (${list.length}) ==`);
  for (const [k, v] of list) {
    const { l } = toHsl(k);
    rep.push(`  ${hex(k)}  px=${String(v.px).padStart(7)}  files=${String(v.files.size).padStart(3)}  L=${l.toFixed(2)}`);
  }
  rep.push('');
}

rep.push('== per-sprite stats (sorted by colour count) ==');
rep.push('  cols  WxH      opq%  semi%  file');
for (const f of perFile.sort((a, b) => b.colors - a.colors)) {
  const total = f.opaque + f.transparent + f.semi;
  rep.push(`  ${String(f.colors).padStart(4)}  ${`${f.width}x${f.height}`.padEnd(8)} ${(100 * f.opaque / total).toFixed(0).padStart(4)}% ${(100 * f.semi / total).toFixed(1).padStart(5)}%  ${f.file}`);
}

const semiTotal = perFile.reduce((s, f) => s + f.semi, 0);
const pxTotal = perFile.reduce((s, f) => s + f.opaque + f.transparent + f.semi, 0);
rep.push('');
rep.push(`Semi-transparent pixels overall: ${semiTotal} of ${pxTotal} (${(100 * semiTotal / pxTotal).toFixed(2)}%) — alpha is ${semiTotal / pxTotal < 0.01 ? 'effectively BINARY' : 'NOT binary'}.`);

fs.mkdirSync(path.join(ROOT, 'spritefactory', 'reports'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'spritefactory', 'reports', 'palette-report.txt'), rep.join('\n'));

console.log(rep.slice(0, 8).join('\n'));
console.log(`...\nWrote lib/palette-data.mjs (${CANON.length} colours) and reports/palette-report.txt`);
