import Phaser from 'phaser';

import { FONT_FAMILY, TEXT_RESOLUTION } from '@/game/constants';
import { getSoundManager } from '@/game/audio/SoundManager';
import { setActiveLevel, levelFilePath } from '@/game/runtime/activeLevel';
import { t } from '@/game/i18n/i18n';
import { preloadTextures3D } from '@/game/render3d/textures3d';
import { setWorldData } from '@/game/world/WorldData';

// The "Jogar levels" screen: the list of standalone puzzle levels, read at runtime from
// public/levels/index.json (a static file — works in dev and the published build alike). Picking
// one loads its world (public/levels/level-N.json) into WorldData and boots the GameScene; ESC /
// "Voltar" returns to the title. The manifest is generated by scripts/gen-levels.mjs, so the list
// stays in sync with the level files without this scene scanning a directory (impossible in a
// static build).
const ACCENT = 0xf5d97a;
const ROW_FILL = 0x14141f;
const ROW_FILL_SEL = 0x22222f;
const ROW_STROKE = 0x3a3a4a;

interface LevelEntry {
  file: string;
  name: string;
  blurb?: string;
  level: number; // the 1-based number parsed from the file/id
}

interface Row {
  bg: Phaser.GameObjects.Rectangle;
  name: Phaser.GameObjects.Text;
  blurb?: Phaser.GameObjects.Text;
  activate: () => void;
}

export class LevelSelectScene extends Phaser.Scene {
  public static readonly key = 'levelselect';

  private rows: Row[] = [];
  private selected = 0;
  private starting = false;
  private heading?: Phaser.GameObjects.Text;
  private status?: Phaser.GameObjects.Text;

  public constructor() {
    super(LevelSelectScene.key);
  }

  public create(): void {
    const { width, height } = this.scale;
    this.rows = [];
    this.selected = 0;
    this.starting = false;
    this.cameras.main.setBackgroundColor('#08080d');
    this.cameras.main.fadeIn(400, 0, 0, 0);

    this.heading = this.add
      .text(width / 2, Math.round(height * 0.14), t('levelSelect.heading'), {
        fontFamily: FONT_FAMILY,
        fontSize: `${Phaser.Math.Clamp(Math.floor(width / 26), 12, 28)}px`,
        color: '#e7dcc4',
        resolution: TEXT_RESOLUTION,
      })
      .setOrigin(0.5)
      .setDepth(2);

    this.status = this.add
      .text(width / 2, Math.round(height * 0.5), t('levelSelect.loading'), {
        fontFamily: FONT_FAMILY,
        fontSize: `${Phaser.Math.Clamp(Math.floor(width / 46), 9, 15)}px`,
        color: '#8a8594',
        resolution: TEXT_RESOLUTION,
      })
      .setOrigin(0.5)
      .setDepth(2);

    // Always offer a way back, even before/if the list fails to load.
    this.makeBackButton();

    // Arm keys a beat later so the key/tap that left the title can't pick a level instantly.
    this.time.delayedCall(300, () => {
      this.input.keyboard?.on('keydown', this.handleKey, this);
    });
    this.events.once(Phaser.Scenes.Events.SHUTDOWN, this.teardown, this);

    void this.loadManifest();
  }

  private async loadManifest(): Promise<void> {
    let entries: LevelEntry[] = [];
    try {
      const res = await window.fetch(`${import.meta.env.BASE_URL}levels/index.json`);
      if (res.ok) {
        const raw = (await res.json()) as Array<{ file?: string; id?: string; name?: string; blurb?: string }>;
        entries = raw
          .map((e): LevelEntry | null => {
            const match = /(\d+)/u.exec(e.file ?? e.id ?? '');
            if (!match || !e.file || !e.name) return null;
            return { file: e.file, name: e.name, blurb: e.blurb, level: Number(match[1]) };
          })
          .filter((e): e is LevelEntry => e !== null);
      }
    } catch {
      /* offline / malformed — falls through to the empty state */
    }

    if (this.starting) return; // scene left while fetching
    this.status?.destroy();
    this.status = undefined;

    if (entries.length === 0) {
      this.status = this.add
        .text(this.scale.width / 2, Math.round(this.scale.height * 0.5), t('levelSelect.empty'), {
          fontFamily: FONT_FAMILY,
          fontSize: `${Phaser.Math.Clamp(Math.floor(this.scale.width / 46), 9, 15)}px`,
          color: '#8a8594',
          resolution: TEXT_RESOLUTION,
        })
        .setOrigin(0.5)
        .setDepth(2);
      return;
    }

    this.buildRows(entries);
  }

  private buildRows(entries: LevelEntry[]): void {
    const { width, height } = this.scale;
    const rowW = Phaser.Math.Clamp(width * 0.6, 240, 520);
    const rowH = Phaser.Math.Clamp(height * 0.12, 52, 92);
    const gap = rowH * 0.28;
    const total = entries.length * rowH + (entries.length - 1) * gap;
    const startY = Math.round(height * 0.52) - total / 2 + rowH / 2;

    entries.forEach((entry, i) => {
      const y = startY + i * (rowH + gap);
      const bg = this.add
        .rectangle(width / 2, y, rowW, rowH, ROW_FILL, 1)
        .setStrokeStyle(2, ROW_STROKE)
        .setDepth(1)
        .setInteractive({ useHandCursor: true });
      const name = this.add
        .text(width / 2, y - (entry.blurb ? rowH * 0.16 : 0), `${entry.level}. ${entry.name}`, {
          fontFamily: FONT_FAMILY,
          fontSize: `${Phaser.Math.Clamp(Math.floor(width / 44), 11, 20)}px`,
          color: '#cfc9bd',
          resolution: TEXT_RESOLUTION,
        })
        .setOrigin(0.5)
        .setDepth(2);
      let blurb: Phaser.GameObjects.Text | undefined;
      if (entry.blurb) {
        blurb = this.add
          .text(width / 2, y + rowH * 0.24, entry.blurb, {
            fontFamily: FONT_FAMILY,
            fontSize: `${Phaser.Math.Clamp(Math.floor(width / 84), 7, 12)}px`,
            color: '#7f7a86',
            resolution: TEXT_RESOLUTION,
            align: 'center',
            wordWrap: { width: rowW - 24 },
          })
          .setOrigin(0.5)
          .setDepth(2);
      }

      const index = i;
      bg.on(Phaser.Input.Events.POINTER_OVER, () => this.setSelected(index));
      bg.on(Phaser.Input.Events.POINTER_DOWN, () => { this.setSelected(index); this.play(entry); });
      this.rows.push({ bg, name, blurb, activate: () => this.play(entry) });
    });

    this.applySelection();
  }

  private makeBackButton(): void {
    const { width, height } = this.scale;
    const y = Math.round(height * 0.92);
    const label = this.add
      .text(width / 2, y, `‹ ${t('levelSelect.back')}`, {
        fontFamily: FONT_FAMILY,
        fontSize: `${Phaser.Math.Clamp(Math.floor(width / 64), 8, 13)}px`,
        color: '#8a8594',
        resolution: TEXT_RESOLUTION,
      })
      .setOrigin(0.5)
      .setDepth(2)
      .setInteractive({ useHandCursor: true });
    label.on(Phaser.Input.Events.POINTER_OVER, () => label.setColor('#fff2c8'));
    label.on(Phaser.Input.Events.POINTER_OUT, () => label.setColor('#8a8594'));
    label.on(Phaser.Input.Events.POINTER_DOWN, () => this.back());
  }

  private setSelected(index: number): void {
    if (this.starting || index === this.selected) return;
    this.selected = index;
    this.applySelection();
    getSoundManager().playWaterDrop();
  }

  private move(delta: number): void {
    const n = this.rows.length;
    if (n === 0) return;
    this.setSelected((this.selected + delta + n) % n);
  }

  private applySelection(): void {
    this.rows.forEach((row, i) => {
      const sel = i === this.selected;
      row.bg.setFillStyle(sel ? ROW_FILL_SEL : ROW_FILL, 1);
      row.bg.setStrokeStyle(sel ? 3 : 2, sel ? ACCENT : ROW_STROKE);
      row.name.setColor(sel ? '#fff2c8' : '#cfc9bd');
      row.blurb?.setColor(sel ? '#b3a9a0' : '#7f7a86');
    });
  }

  private readonly handleKey = (event: KeyboardEvent): void => {
    if (this.starting) return;
    switch (event.key) {
      case 'ArrowUp':
      case 'ArrowLeft':
        this.move(-1);
        break;
      case 'ArrowDown':
      case 'ArrowRight':
        this.move(1);
        break;
      case 'Enter':
      case ' ':
        this.rows[this.selected]?.activate();
        break;
      case 'Escape':
      case 'Backspace':
        this.back();
        break;
      default:
        break;
    }
  };

  private back(): void {
    if (this.starting) return;
    this.starting = true;
    this.cameras.main.fadeOut(350, 0, 0, 0);
    this.cameras.main.once(Phaser.Cameras.Scene2D.Events.FADE_OUT_COMPLETE, () => this.scene.start('title'));
  }

  private play(entry: LevelEntry): void {
    if (this.starting) return;
    this.starting = true;
    getSoundManager().unlock();
    this.cameras.main.fadeOut(400, 0, 0, 0);
    this.cameras.main.once(Phaser.Cameras.Scene2D.Events.FADE_OUT_COMPLETE, () => {
      void window
        .fetch(levelFilePath(entry.level))
        .then((res) => res.json())
        .then((world) => {
          setWorldData(world);
          setActiveLevel(entry.level);
          return preloadTextures3D();
        })
        .then(() => this.scene.start('game'))
        .catch(() => {
          // The level file failed to load — go back to the list rather than boot a blank world.
          this.starting = false;
          this.scene.restart();
        });
    });
  }

  private teardown(): void {
    this.input.keyboard?.off('keydown', this.handleKey, this);
  }
}
